function [optionsga] = options_GA(GenLimit, PopulationSize, InitialPopulation,...
    tolfun, StallGenLimit_VAL, maxtime)

optionsga = gaoptimset('DistanceMeasureFcn',{@distancecrowding,'genotype'},...
    'Generations', GenLimit,...
    'PopulationSize', PopulationSize,...
    'InitialPopulation', InitialPopulation,...
    'TolFun', tolfun,...
    'Display', 'off',...
    'StallGenLimit',StallGenLimit_VAL,...
    'TimeLimit', maxtime);
optionsga.PlotFcns    = @gaplotscores;
optionsga.UseParallel = true;

end